# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a8y9WSefCpmRPV69B3KhBdnd3wQ0A6b2
"""

import nltk

# Create a text summarization model
model = nltk.corpus.stopwords.words('english')

# Summarize the text
summary = ' '.join([word for word in text if word not in model])

from gensim.summarization.summarizer import summarize
from gensim.summarization import keywords
import wikipedia

# Your text goes here
text = wikipedia.page("Mount Everest").content

# Summarize the text
summarized_text = summarize(text)

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.text_rank import TextRankSummarizer

# Your text goes here
text = "Your long test text..."

# Create a text parser using tokenization
parser = PlaintextParser.from_string(text, Tokenizer("english"))

# Summarize the text using TextRank
summarizer = TextRankSummarizer()
summary = summarizer(parser.document, sentences_count=3)  # Adjust the number of sentences as needed
for sentence in summary:
    print(sentence)